language: node_js
node_js: '10.15'
cache: npm
sudo: required
install:
  - npm i -g gulp
  - npm i
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: gh-pages